<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ichapp_site"
 *
 * Auto generated by Extension Builder 2019-09-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Build Information',
    'description' => 'Plugin contains system information messages for the current build number and the current build date and age.',
    'category' => 'plugin',
    'author' => 'Klaus Hörmann-Engl',
    'author_email' => 'kho@world-direct.at',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.15-10.4.99',
            'fluid_styled_content' => '9.5.15-10.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
