services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WorldDirect\Buildinfo\:
    resource: '../Classes/*'
  
  WorldDirect\Buildinfo\SystemInformation\ToolbarItemProvider:
    tags:
      - name: event.listener
        identifier: 'buildinfo/show-current-buildnumber'
        method: 'getBuildNumber'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
      - name: event.listener
        identifier: 'buildinfo/show-current-buildtimestamp'
        method: 'getBuildDate'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
      - name: event.listener
        identifier: 'buildinfo/show-current-gitVersion'
        method: 'getGitVersion'
        event: TYPO3\CMS\Backend\Backend\Event\SystemInformationToolbarCollectorEvent
  # Needed for DI to work in this class
  WorldDirect\Buildinfo\Service\ToolbarService:
    public: true
